### ISSUE TITLE
Support for ignore file

### ISSUE THREAD

**Issue by nikolailehbrink** [Dylan700/sftp-upload-action#13]
Hello,

first, I would like to thank you for the sftp-deploy GitHub Action. It has been very helpful for our project deployment process.

However, I noticed that the current implementation of the action supports the ignore flag for specifying individual patterns to exclude, but it does not support using an external file for managing the ignore patterns.

It would be great if you could add support for using an ignore file, similar to how the rsync command supports the --exclude-from flag. This would allow us to manage and update the list of files and folders to exclude more efficiently, keeping the workflow file cleaner.

Here's an example of how the proposed functionality could be used:

```yaml
- name: 📂 Sync files
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          uploads: |
            ./ => ./www/public_html/
          ignore: .github/workflows/deploy/sftp-ignore.txt
```

In this example, the ignore-file option specifies the path to a file containing the ignore patterns, similar to how rsync works with the [--exclude-from](https://phoenixnap.com/kb/rsync-exclude-files-and-directories#ftoc-heading-8) flag.

Please let me know if this is something you would consider adding to your action. I believe it would be a valuable addition for users who need to manage a more complex list of exclusions.
