### ISSUE TITLE
Specifying which files to upload

### ISSUE THREAD

**Issue by bobmulder** [Dylan700/sftp-upload-action#17]
Hi Dylan,

Thank you for the work on this action, it helped me a lot.

Currently, uploading my complete `dist` folder takes about 2 minutes. I'd like to specify which files to upload like so:

```yml
      - name: Upload assets (js, css)
        if: steps.check_commit.outputs.full_upload != 'true'
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{secrets.SERVER}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: 22
          uploads: |
            ./dist/style.css => ./github-actions-test # specifying the file
            ./dist/*.js => ./github-actions-test # specifying the type of file
```

I have no clue is this is difficult to implement, but I'd be happy to help.

**Comment by Dylan700** [comment]
Hi Bob,

Thanks for using my action! 

Pull requests and improvements are certainly welcome, happy to point you in the right direction regarding the implementation too. 

If you just want to upload a few files, you can do this as per https://github.com/Dylan700/sftp-upload-action#upload-specific-files. Essentially, you just tell it which folders you want to upload, then ignore everything except the files you wish to upload.

So based on your above scenario it should be:

```yaml
      - name: Upload assets (js, css)
        if: steps.check_commit.outputs.full_upload != 'true'
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{secrets.SERVER}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: 22
          uploads: |
            ./dist/ => ./github-actions-test # specifying the folder
          ignore: | # specifying the exact files
            !style.css
            !*.js
```

If you want a more explicit or complicated file selection then you may need to submit a pull request. But hopefully this helps ;)
