### ISSUE TITLE
Exclude folder with ingore

### ISSUE THREAD

**Issue by zvassos** [Dylan700/sftp-upload-action#33]
Hello thx for the Action!

Trying to exclude specific folders from uploading but it does not seem to work.

I'm uploading ./wp-content/ => {remote_path}/wp-content/ and it works, but excluding e.g. "wp-content/themes/{theme_name}/js/" does not work, am i missing something?

Thx alot!

**Comment by Dylan700** [comment]
Hi @zvassos, 

Try this, I think you need to specify what to ignore in terms of files, not a directory:

 ```
- name: Checkout
  uses: actions/checkout@v4
- name: SFTP upload
  uses: Dylan700/sftp-upload-action@latest
  with:
    server: sftp.server.com
    username: jason-bourne
    key: ${{secrets.key}}
    passphrase: ${{secrets.passphrase}}
    port: 22
    uploads: |
      /wp-content/ => {remote_path}/wp-content/
    ignore: | wp-content/themes/{theme_name}/js/*.js
```

Let me know how you go!
